
import './globals.css'
import type { Metadata } from 'next'
import { Inter, Roboto_Flex } from 'next/font/google'
import localFont from 'next/font/local'
import Navbar from '@/components/Navbar'
import { ThemeProvider } from '@/components/theme/themeProvider'
const ClashFont = localFont({
  src: '../ClashDisplay-Medium.otf',
  display: 'swap',
  variable:'--font-clash'
})
const Roboto =  Roboto_Flex({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-roboto-flex',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (

    <html lang="en">
      
      <body className={`${ClashFont.variable} ${Roboto.variable}`}>
        <ThemeProvider  attribute="class" defaultTheme="system" enableSystem>
       <Navbar/>
       <div className='m-10'>
        {children}
        </div>
        </ThemeProvider>
      </body>
    </html>
   
  )
}
  